project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - "articles/*.ipynb"
    - "!articles/_*.ipynb"

website:
  title: "drnb notebooks"
  site-url: "https://jlmelville.github.io/drnb/"
  repo-url: "https://github.com/jlmelville/drnb"
  navbar:
    left:
      - href: index.qmd
        text: Notebooks
      - href: https://github.com/jlmelville/drnb
        text: GitHub
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - section: "Articles"
        contents:
          - text: Do Hubs Hurt?
            href: articles/do-hubs-hurt.ipynb
          - text: How Does Dimensionality Reduction Transform Distances?
            href: articles/embed-distances.ipynb
          - text: Hubness
            href: articles/hubness.ipynb
          - text: Heavy-tailed UMAP
            href: articles/htumap.ipynb
          - text: "Leopold: Lightweight Estimate of Preservation of Local Density"
            href: articles/leopold.ipynb
          - text: Measuring Media Bias
            href: articles/mediabias.ipynb
          - text: Normalized Compression Distance with 20 Newsgroups
            href: articles/ncd-newsgroups.ipynb
          - text: "PaCMAP: local scaling vs. k-nearest neighbors"
            href: articles/pacmap-local-scaling.ipynb
          - text: PaCMAP Repeats
            href: articles/pacmap-repeats.ipynb
          - text: Neighbor Overlap and PCA
            href: articles/pca-nn-overlap.ipynb
          - text: "Neighbor Recall: UMAP vs t-SNE"
            href: articles/recall.ipynb
          - text: Approximating Isomap with k-Nearest Neighbors and Stochastic Metric Multidimensional Scaling
            href: articles/sikmmds.ipynb
          - text: Stochastic Metric Multidimensional Scaling
            href: articles/smmds.ipynb
          - text: Renormalizing after TF-IDF + SVD
            href: articles/tfidf-renorm.ipynb
          - text: t-SNE Consistency with Random Initialization
            href: articles/tsne-repeats.ipynb
          - text: "UMAP with Annealed Neighbors. 1: Defaults"
            href: articles/umap-annealed-neighbors-01.ipynb
          - text: "UMAP with Annealed Neighbors. 2: t-UMAP"
            href: articles/umap-annealed-neighbors-02-tumap.ipynb
          - text: "UMAP with Annealed Neighbors. 3: PCA Initialization"
            href: articles/umap-annealed-neighbors-03-pca.ipynb
          - text: Spectral Embedding
            href: articles/umapspectral.ipynb
          - text: UMATO Evaluation
            href: articles/umato-eval.ipynb
          - text: "t-SNE Affinity: Gaussian vs. Uniform"
            href: articles/tsne-affinity.ipynb

execute:
  enabled: false

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
    include-after-body:
      - _open-image.html
