---
title: "Experiments in Dimensionality Reduction"
---

This site presents some HTML renderings of python notebooks which make use of the `drnb` repo, 
which was created entirely for this purpose. I wanted to:

- wrap existing -- or create new -- dimensionality reduction methods or related techniques.
- preprocess a large number of datasets of various subject matters of interest or amusement to me,
including real-world and synthetic data.
- precalculate nearest neighbors for those datasets to speed up methods which take external
neighbor graphs and remove a source of variability.
- run those different embedding methods on those datasets, controlling as much of the process as
possible.
- produce standardized plots and metrics for me to look at.
- having removed as much frustrating sources of variability as possible, maybe learn something?

My usual strategy is to throw a bunch of stuff at the wall, stare at it for a bit, cluck my tongue
in disappointment and then move on with my life. I don't promise the most scintillating
narratives within.

Built with [quarto](https://quarto.org/), it does its best to make these articles look attractive,
but they do betray their origins as python notebooks.
